services:
  db:
    ports:
      - "5432:5432"
  backend:
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/tests:/app/tests
    command: ["--reload"]
  frontend:
    build:
      target: development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/public:/app/public
  proxy:
    ports:
      - "80:80"
